spring:
  datasource:
    bank:
      jdbc-url: jdbc:postgresql://localhost:5432/bank_test?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123

stresspileServer:
  url: "http://119.45.198.54:8001/webapi/api"
  user: "admin"
  password: "phmpassword"

logpath: "D:/1study/Work/2024_1_10_bank/数据中台/log/app.log"