spring:
  application:
    name: station
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
<<<<<<< HEAD
  port: 9988
=======
  port: 9989
>>>>>>> 0702b42a43b630e0501b3f0f9891176eb06e4759

mybatis:
  configuration:
    call-setters-on-nulls: true