spring:
  datasource:
    shore:
      jdbc-url: jdbc:postgresql://localhost:5432/bank?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456