spring:
  datasource:
    shore:
      jdbc-url: jdbc:postgresql://localhost:5432/bank_test?stringtype=unspecified
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123

logpath: "D:/1study/Work/2024_1_10_bank/数据中台/log/app.log"