spring:
  application:
    name: station
  profiles:
    active: prod
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 9999
  additionalPorts: 9998,9997,9996

mybatis:
  configuration:
    call-setters-on-nulls: true